### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by widemen** [useragents/Proxyless-TikTok-Username-Checker#14]
every time i try to run the command pip install -r requirements.txt it keeps saying "ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt' " and i do not know how to fix it can one of yall help?

**Comment by widemen** [comment]
nvm i got it now

**Comment by useragents** [comment]
This is either because you don't have `requirements.txt` saved or you are not in the correct directory where the file is located.
Please read [here](https://stackoverflow.com/questions/7225900/how-can-i-install-packages-using-pip-according-to-the-requirements-txt-file-from) if you are still having issues.
