### ISSUE TITLE
CMD issue

### ISSUE THREAD

**Issue by yGermaa** [useragents/Proxyless-TikTok-Username-Checker#42]
when I write "pip install -r requirements.txt" on cmd, this don't found it

**Comment by useragents** [comment]
This issue is not related to my script. This is because the Command Prompt is not in the correct directory, please view [here](https://stackoverflow.com/questions/7225900/how-can-i-install-packages-using-pip-according-to-the-requirements-txt-file-from) to learn how to install requirements from a text file.
